### ISSUE TITLE
Repositories: To-Create Collection (1)

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [AFg6K7h4fhy2/AFg6K7h4fhy2#1]
This issue collects the repositories that AFg6K7h4fhy2 desires to setup. Repositories that are expected to always be private are not included here for privacy. Public commentary on the utility of these repositories to the life of AFg6K7h4fhy2 are welcome. There are no standards AFg6K7h4fhy2 has adopted for describing these repositories, but in some instances, the repositories may contain short descriptions and or setup or design notes. 

* [ ] Collection Of Reproducibility Practices
* [ ] Collection Of Genetic-Engineering Repositories Relevant To Humans 
* [ ] Expanded Toolset For The Paleobiology Database
* [x] Genetic Evolution Tournament 
* [ ] Collection Of Implemented Linear Optimization Artworks
* [ ] Collection Of Template Design For Repositories
* [ ] Pandoc Template
* [x] Forecasting-Tornadoes 
* [x] Forecasting-Measles (not public)
* [ ] Forecasting-Sea-Ice (not public)
* [ ] Forecasting-Influenza (not public)
* [x] Forecasting-HJF-Personal (not public)
* [ ] Toolset For Decision Making
* [x] Metaculus-Utils (not public)
* [x] PaleoDB-Utils (not public)
* [ ] Collection Of Polygenic Screening Repositories
* [ ] General Repository Template
* [ ] Light Database Template
* [ ] Multiple-Model Experimental Template
* [ ] Single-Model Experimental Template
* [ ] Package And Or Tool Template
* [ ] Information Collection Template
* [ ] Paper Reviews And Notes (x100)
* [ ] Book Chapter Reviews And Notes (x100)
* [ ] Textbook Exercises
* [ ] Anki Cards Database
* [ ] Glossary Database
* [ ] House Documentation Collection
* [ ] Metaculus Participation

**Comment by AFg6K7h4fhy2** [comment]
I no longer believe[^caveat] that an issue is a reasonable location to store repositories that I expect I might create. As such, I am closing this issue as not planned. 

[^caveat]: A caveat here could be that, upon creating a new GitHub account, one might want to have a short list of repositories one is already quite confident that they'll be working on.
