### ISSUE TITLE
General List Of Lists

### ISSUE THREAD

**Issue by AFg6K7h4fhy2** [AFg6K7h4fhy2/AFg6K7h4fhy2#4]
## Goal

Create the following lists of current and future personal enterprises. 

## Tasks

List of...

* [ ] GitHub Projects
* [ ] GitHub Repository List Categories
* [ ] GitHub Repository Lists By Category
* [ ] Repository And Development Decisions 
* [ ] Repository To Create
* [ ] General Ideas
* [ ] Templates To Create

## Out Of Scope

- Further considerations on the content of any of the above lists. 

## Resources & Links

- [pending]

**Comment by AFg6K7h4fhy2** [comment]
As per #3 , the development of lists that the author utilizes for organizing code-development heuristics and patterns, among other things, does not seem appropriate a task to conduct in GitHub issues.
